import { rand } from "./random";
import type { PlingQuestion } from "./pling-plong";

export type PlingSubject =
  | "geografi"
  | "historia"
  | "religion"
  | "samhallskunskap"
  | "biologi"
  | "fysik"
  | "kemi"
  | "teknik"
  | "hem-och-konsumentkunskap"
  | "engelska"
  | "svenska";

export const PLING_SUBJECTS: Record<PlingSubject, string> = {
  geografi: "Geografi",
  historia: "Historia",
  religion: "Religion",
  samhallskunskap: "Samhällskunskap",
  biologi: "Biologi",
  fysik: "Fysik",
  kemi: "Kemi",
  teknik: "Teknik",
  "hem-och-konsumentkunskap": "Hem- och konsumentkunskap",
  engelska: "Engelska",
  svenska: "Svenska",
};

const QUESTION_BANK: Record<PlingSubject, readonly [string, string][]> = {
  geografi: [
    ["Vilka tre landsdelar brukar Sverige delas in i?", "Norrland, Svealand och Götaland"],
    ["Vilket land gränsar Sverige till i väster?", "Norge"],
    ["Vilket land gränsar Sverige till i öster?", "Finland"],
    ["Vad heter Sveriges största sjö?", "Vänern"],
    ["Vad kallas en ritad bild av ett område sedd uppifrån?", "Karta"],
    ["Vilket väderstreck ligger till höger på en vanlig karta?", "Öster"],
    ["Vad heter Sveriges huvudstad?", "Stockholm"],
    ["Vilket hav ligger mellan Sverige och Finland?", "Östersjön"],
    ["Vad visar en kartas teckenförklaring?", "Vad kartans symboler betyder"],
    ["Vad kallas en plats där en älv rinner ut i havet?", "Mynning"],
  ],
  historia: [
    ["Vad kallas tiden då människor började odla och hålla tamdjur?", "Bondestenåldern"],
    ["Vad kallades nordbor som reste och handlade för över tusen år sedan?", "Vikingar"],
    ["Vilket år blev Gustav Vasa kung i Sverige?", "1523"],
    ["Vad kallas tiden då maskiner och fabriker förändrade samhället?", "Industrialiseringen"],
    ["Vad hette unionen mellan Sverige, Norge och Danmark som bildades 1397?", "Kalmarunionen"],
    ["Vilket århundrade började andra världskriget?", "1900-talet"],
    ["Vad kallas en källa som skapades under tiden man undersöker?", "Primärkälla"],
    ["Vad byggde människor ofta av sten och brons under forntiden?", "Verktyg och redskap"],
    ["Vad kallades de första människorna som levde av jakt och insamling?", "Jägare och samlare"],
    ["Vad innebär det att en historisk källa är muntlig?", "Informationen har berättats med tal"],
  ],
  religion: [
    ["Vilken religion förknippas med högtiden ramadan?", "Islam"],
    ["Vad heter judendomens heliga skrift?", "Torah"],
    ["Vad heter kristendomens heliga skrift?", "Bibeln"],
    ["Vad heter islams heliga skrift?", "Koranen"],
    ["Vad kallas byggnaden där muslimer samlas för bön?", "Moské"],
    ["Vad kallas byggnaden där judar samlas för gudstjänst?", "Synagoga"],
    ["Vad kallas byggnaden där kristna samlas för gudstjänst?", "Kyrka"],
    ["Vilken högtid firar kristna till minne av Jesu födelse?", "Jul"],
    ["Vad heter den judiska ljushögtiden som varar i åtta dagar?", "Chanukka"],
    ["Vilken religion förknippas med högtiden diwali?", "Hinduism"],
  ],
  samhallskunskap: [
    ["Vad betyder demokrati?", "Folkstyre"],
    ["Vad heter Sveriges folkvalda parlament?", "Riksdagen"],
    ["Hur ofta är det val till Sveriges riksdag?", "Vart fjärde år"],
    ["Vad kallas pengar som invånare betalar till det gemensamma?", "Skatt"],
    ["Vad ansvarar en kommun bland annat för?", "Skola och äldreomsorg"],
    ["Vilken myndighet beslutar om lagar i Sverige?", "Riksdagen"],
    ["Vad kallas det när medborgare röstar i ett val?", "Att rösta"],
    ["Vad heter regler som gäller för alla i ett land?", "Lagar"],
    ["Vad är en rättighet?", "Något man har rätt att göra eller få"],
    ["Vad kallas det när människor flyttar från ett land till ett annat?", "Migration"],
  ],
  biologi: [
    ["Vilken gas tar växter upp från luften när de fotosyntetiserar?", "Koldioxid"],
    ["Vilken gas släpper växter ut vid fotosyntes?", "Syre"],
    ["Vilken del av växten tar oftast upp vatten ur marken?", "Rötterna"],
    ["Vad kallas djur som bara äter växter?", "Växtätare"],
    ["Vilket organ pumpar runt blodet i kroppen?", "Hjärtat"],
    ["Vilka organ använder kroppen för att ta upp syre ur luften?", "Lungorna"],
    ["Vad kallas en kedja som visar vem som äter vem i naturen?", "Näringskedja"],
    ["Vad behöver frön ofta för att börja gro?", "Vatten, värme och syre"],
    ["Vad kallas djur som har ryggrad?", "Ryggradsdjur"],
    ["Vilken insekt hjälper ofta till att pollinera blommor?", "Biet"],
  ],
  fysik: [
    ["Vad drar föremål mot marken?", "Tyngdkraften"],
    ["Vad kallas det när vatten blir till is?", "Frysning"],
    ["Vad kallas det när is blir till flytande vatten?", "Smältning"],
    ["Vad behöver en enkel elektrisk krets för att lampan ska lysa?", "En sluten krets"],
    ["Vilken kraft gör det svårare för saker att glida?", "Friktion"],
    ["Vad kan en magnet dra till sig som ofta finns i stål?", "Järn"],
    ["Vad färdas snabbast, ljud eller ljus?", "Ljus"],
    ["Vad kallas energi från solen?", "Solenergi"],
    ["Vad bildas när vatten kokar och blir gas?", "Vattenånga"],
    ["Vad behöver ljud för att kunna spridas?", "Ett material att färdas genom"],
  ],
  kemi: [
    ["Vad är vatten uppbyggt av för två grundämnen?", "Väte och syre"],
    ["Vilken kemisk formel har vatten?", "H₂O"],
    ["Vad kallas det när ett ämne blandas jämnt med en vätska?", "Lösning"],
    ["Vad kan man använda för att skilja sand från vatten?", "Ett filter"],
    ["Vad behöver en eld oftast för att fortsätta brinna?", "Syre"],
    ["Vad kallas ämnen som bygger upp allt material omkring oss?", "Atomer"],
    ["Vad händer med vatten när det avdunstar?", "Det blir vattenånga"],
    [
      "Vad kan en magnet användas till vid sortering av metall?",
      "Att skilja järn från andra material",
    ],
    ["Vilket pH-värde har en neutral lösning?", "7"],
    ["Vad kallas det när ett material förändras och ett nytt ämne bildas?", "Kemisk reaktion"],
  ],
  teknik: [
    ["Vad kallas en ritning som visar hur en lösning ska byggas?", "Konstruktionsritning"],
    ["Vilken enkel maskin finns i en gungbräda?", "Hävstång"],
    ["Vad kallas en kedja av delar där rörelse förs vidare?", "Mekanism"],
    [
      "Varför byggs broar ofta med trianglar i konstruktionen?",
      "Trianglar gör konstruktionen stabil",
    ],
    ["Vad används en skruv till?", "Att fästa eller lyfta saker"],
    ["Vad kallas det när man provar en lösning för att se om den fungerar?", "Testning"],
    ["Vad gör en strömbrytare i en elektrisk krets?", "Öppnar eller sluter kretsen"],
    ["Vad är ett exempel på en förnybar energikälla?", "Solenergi"],
    ["Vilket material används ofta för att göra elektriska ledningar?", "Koppar"],
    ["Vad kallas en plan för hur en teknisk lösning ska fungera?", "En design eller konstruktion"],
  ],
  "hem-och-konsumentkunskap": [
    ["Vad betyder bäst före-datum på en matvara?", "Kvaliteten kan vara bäst före det datumet"],
    ["Vad bör man göra med händerna innan man lagar mat?", "Tvätta dem"],
    ["Vad visar innehållsförteckningen på en matvara?", "Vilka ingredienser den innehåller"],
    ["Vad kallas en plan för vilka måltider man ska laga?", "Matsedel"],
    [
      "Varför är det bra att jämföra priser när man handlar?",
      "För att hitta ett bra pris och använda pengarna klokt",
    ],
    ["Vad bör man göra med rå kyckling innan den äts?", "Tillaga den ordentligt"],
    [
      "Vad betyder det att återvinna en förpackning?",
      "Lämna den så att materialet kan användas igen",
    ],
    ["Vad är en budget?", "En plan för inkomster och utgifter"],
    [
      "Vad kan en miljömärkning hjälpa konsumenten att se?",
      "Att en vara uppfyller vissa miljökrav",
    ],
    ["Varför ska rå och färdiglagad mat hållas åtskilda?", "För att minska risken för smitta"],
  ],
  engelska: [
    ["Vad betyder det engelska ordet “apple”?", "Äpple"],
    ["Hur säger man “tack” på engelska?", "Thank you"],
    ["Vad betyder “Where do you live?”", "Var bor du?"],
    ["Vilket engelskt ord betyder “skola”?", "School"],
    ["Vad är pluralformen av “child”?", "Children"],
    ["Vad betyder “yesterday”?", "I går"],
    ["Vilket engelskt ord betyder “blå”?", "Blue"],
    ["Hur säger man “God morgon” på engelska?", "Good morning"],
    ["Vad betyder “I like reading”?", "Jag tycker om att läsa"],
    ["Vilken årstid heter “winter” på svenska?", "Vinter"],
  ],
  svenska: [
    ["Vad kallas ord som beskriver substantiv, till exempel glad eller blå?", "Adjektiv"],
    ["Vad kallas ord som berättar vad någon gör?", "Verb"],
    ["Vad kallas ord för personer, platser och saker?", "Substantiv"],
    ["Vilket skiljetecken avslutar oftast en fråga?", "Frågetecken"],
    ["Vad kallas ett ord som betyder nästan samma sak som ett annat?", "Synonym"],
    ["Vad kallas ett ord som betyder motsatsen till ett annat?", "Antonym"],
    ["Vad kallas en person som berättar en historia?", "Berättare"],
    ["Vad ska man skriva i början av en mening?", "Stor bokstav"],
    ["Vad kallas en text som berättar hur något gått till?", "Berättande text"],
    ["Vad är en källa när man söker fakta?", "Där informationen kommer ifrån"],
  ],
};

const CONCEPT_FACTS: Record<PlingSubject, readonly [string, string][]> = {
  geografi: [
    ["en ekvator", "en tänkt linje runt jordens mitt"],
    ["en breddgrad", "ett mått på hur långt norr eller söder en plats ligger"],
    ["en längdgrad", "ett mått på hur långt öster eller väster en plats ligger"],
    ["en kontinent", "ett av jordens stora sammanhängande landområden"],
    ["en halvö", "ett landområde som nästan helt omges av vatten"],
    ["en ö", "ett landområde som omges av vatten"],
    ["en skärgård", "en grupp öar nära en kust"],
    ["en kust", "gränsen mellan land och hav"],
    ["ett sund", "en smal vattenväg mellan två landområden"],
    ["en vik", "en del av havet som går in i land"],
    ["en glaciär", "en stor massa is som rör sig långsamt"],
    ["en källa", "platsen där en bäck eller älv börjar"],
    ["ett delta", "ett landområde som bildas där en flod delar upp sig vid sin mynning"],
    ["en platå", "ett högt och ganska platt landområde"],
    ["en dal", "ett lägre landområde mellan höjder eller berg"],
    ["en bergskedja", "en lång rad berg som hör ihop"],
    ["en vulkan", "en öppning i jordskorpan där lava och gaser kan komma ut"],
    ["en jordbävning", "markens skakningar när delar av jordskorpan rör sig"],
    ["en naturresurs", "något från naturen som människor kan använda"],
    ["en råvara", "ett material som används för att tillverka något"],
    ["en tätort", "ett sammanhängande område med många bostäder nära varandra"],
    ["glesbygd", "ett område där människor bor glest och långt från varandra"],
    ["en huvudstad", "den stad där ett lands regering oftast finns"],
    ["en tidszon", "ett område där klockan har samma normaltid"],
    ["en kartskala", "förhållandet mellan avstånd på kartan och avstånd i verkligheten"],
    ["en teckenförklaring", "delen av en karta som visar vad kartans symboler betyder"],
    ["en kompassros", "en symbol på kartan som visar väderstrecken"],
    ["nederbörd", "vatten som faller från moln som regn, snö eller hagel"],
    ["ett klimat", "det vanliga vädret i ett område under lång tid"],
    ["en väderprognos", "en beräkning av hur vädret väntas bli"],
    ["en naturkatastrof", "en allvarlig händelse i naturen som orsakar stor skada"],
    ["erosion", "när jord och berg nöts bort av exempelvis vatten eller vind"],
    ["grundvatten", "vatten som finns i marken mellan jord och berg"],
    ["en vattenåder", "ett lager i marken där grundvatten samlas och rör sig"],
    ["en älv", "ett större rinnande vattendrag som ofta rinner mot havet"],
    ["en insjö", "en sjö som ligger inne i landet"],
    ["en fjord", "en lång och smal havsvik med branta sidor"],
    ["en förnybar resurs", "en naturresurs som fylls på naturligt på relativt kort tid"],
    ["en gräns", "en linje som skiljer länder eller områden åt"],
    ["en befolkning", "alla människor som bor i ett visst område"],
    ["en befolkningstäthet", "hur många människor som bor på en viss yta"],
    ["en hamn", "en plats vid vatten där båtar kan lägga till"],
    ["jordbruk", "odling av växter och uppfödning av djur för mat och material"],
    ["fiske", "att fånga fisk och andra djur som lever i vatten"],
    ["en nordpol", "den nordligaste punkten på jordens rotationsaxel"],
    ["en sydpol", "den sydligaste punkten på jordens rotationsaxel"],
  ],
  historia: [
    ["arkeologi", "att undersöka spår och föremål från människors liv förr"],
    ["en historisk källa", "något som kan ge information om det som hänt förr"],
    ["en primärkälla", "en källa som skapades nära den tid eller händelse den berättar om"],
    ["en muntlig källa", "information som någon har berättat med tal"],
    ["en runsten", "en sten med text ristad med runor"],
    ["en runa", "ett tecken i ett äldre nordiskt skriftsystem"],
    ["jägare och samlare", "människor som fick mat genom jakt och genom att samla växter"],
    ["en bonde", "en person som odlar mark eller föder upp djur"],
    ["en forntid", "en tid långt tillbaka innan den vanliga skrivna historien"],
    ["en medeltid", "en historisk period mellan forntiden och den tidigmoderna tiden"],
    ["en stormakt", "ett land som har stor makt och stort inflytande"],
    ["en union", "ett samarbete där flera länder har en gemensam ledare eller styrelse"],
    ["Kalmarunionen", "en union mellan Danmark, Norge och Sverige som bildades 1397"],
    ["en reformation", "en förändring som ledde till att kyrkan delades i olika riktningar"],
    ["protestantism", "en riktning inom kristendomen som växte fram efter reformationen"],
    ["en upptäcktsresa", "en lång resa för att undersöka eller hitta nya vägar och platser"],
    ["en handelsvara", "en vara som köps och säljs"],
    ["en handelsväg", "en väg eller rutt som människor använde för att handla"],
    ["en koloni", "ett område som styrs av ett annat land"],
    ["en revolution", "en snabb och stor förändring av hur ett land styrs eller fungerar"],
    ["industrialisering", "när tillverkning flyttade till fabriker med maskiner"],
    ["en fabrik", "en byggnad där varor tillverkas, ofta med hjälp av maskiner"],
    ["en uppfinning", "en ny sak eller metod som någon har kommit på"],
    ["en arbetare", "en person som utför ett arbete, ofta mot lön"],
    ["en strejk", "när arbetare slutar arbeta tillsammans för att påverka villkor"],
    ["barnarbete", "när barn tvingas arbeta i stället för att gå i skolan och leka"],
    ["en rösträtt", "rätten att rösta i val"],
    ["allmän rösträtt", "att alla vuxna medborgare får rösta enligt samma regler"],
    ["en folkrörelse", "en stor grupp människor som arbetar tillsammans för en förändring"],
    ["en utvandring", "när människor lämnar sitt land för att bosätta sig någon annanstans"],
    ["en invandring", "när människor flyttar till ett land för att bosätta sig där"],
    ["en tidslinje", "en bild som visar händelser i den ordning de inträffade"],
    ["ett årtionde", "en period som är tio år lång"],
    ["ett århundrade", "en period som är hundra år lång"],
    ["en källa", "något man använder för att ta reda på information"],
    ["ett föremål", "en sak som människor har tillverkat eller använt"],
    ["en lämning", "ett spår från människor som levde förr"],
    ["en tradition", "ett sätt att fira eller göra något som förs vidare mellan generationer"],
    ["en historisk person", "en människa som levde förr och påverkat historien"],
    ["ett världskrig", "ett krig där många länder i olika delar av världen deltar"],
    ["en fred", "ett tillstånd där det inte pågår krig mellan parter"],
    ["en viking", "en person från Norden under vikingatiden"],
    ["vikingatiden", "perioden i Norden ungefär från slutet av 700-talet till 1000-talet"],
    ["en medeltida borg", "en befäst byggnad som kunde skydda människor under medeltiden"],
    ["en historisk förändring", "en förändring i människors liv eller samhälle över tid"],
  ],
  religion: [
    ["en helig skrift", "en text som är särskilt viktig inom en religion"],
    ["en gudstjänst", "en samling där människor ber, sjunger eller läser heliga texter"],
    ["en bön", "ord som en människa riktar till Gud eller det heliga"],
    ["en religiös högtid", "en särskild dag eller period som firas inom en religion"],
    ["ramadan", "den månad då muslimer fastar från gryning till solnedgång"],
    ["eid al-fitr", "en muslimsk högtid som avslutar fastemånaden ramadan"],
    ["moské", "en byggnad där muslimer samlas för bön och gemenskap"],
    ["Koranen", "islams heliga skrift"],
    ["en imam", "en religiös ledare inom islam"],
    ["sabbat", "judendomens vilodag som börjar på fredag kväll"],
    ["synagoga", "en byggnad där judar samlas för bön och undervisning"],
    ["Torah", "en central helig text inom judendomen"],
    ["Chanukka", "en judisk ljushögtid som firas under åtta dagar"],
    ["Pesach", "en judisk högtid som minns uttåget ur Egypten"],
    ["kyrka", "en byggnad där många kristna samlas för gudstjänst"],
    ["Bibeln", "kristendomens heliga skrift"],
    ["jul", "en kristen högtid som firas till minne av Jesu födelse"],
    ["påsk", "en kristen högtid som handlar om Jesu död och uppståndelse"],
    ["ett kors", "en symbol som ofta förknippas med kristendomen"],
    ["en präst", "en religiös ledare i många kristna kyrkor"],
    ["hinduism", "en religion som bland annat har gamla rötter i Indien"],
    ["diwali", "en ljushögtid som firas av många hinduer"],
    ["en mandir", "ett hinduiskt tempel"],
    ["karma", "tanken att handlingar kan påverka vad som händer senare"],
    ["återfödelse", "tron att livet börjar på nytt i en ny kropp"],
    ["buddhism", "en religion och livsåskådning som bygger på Buddhas lära"],
    ["Buddha", "en titel som betyder den upplyste och förknippas med buddhismens grundare"],
    ["ett tempel", "en byggnad som används för religiösa handlingar i flera religioner"],
    ["meditation", "en övning där man tränar uppmärksamhet och lugn"],
    ["en symbol", "en bild eller sak som står för en idé eller tro"],
    ["en pilgrim", "en person som reser till en plats som är viktig för tron"],
    ["en pilgrimsresa", "en resa till en plats som är helig eller religiöst viktig"],
    ["en religiös berättelse", "en berättelse som förklarar eller förmedlar tro och värderingar"],
    ["en skapelseberättelse", "en berättelse om hur världen eller livet började"],
    ["en livsregel", "en regel som hjälper människor att leva enligt sin tro"],
    ["en högtid", "en dag eller period som människor firar särskilt"],
    ["en tradition", "ett sätt att fira eller göra något som förs vidare"],
    ["religionsfrihet", "rätten att tro på en religion eller att inte tro"],
    ["en livsåskådning", "en persons tankar om livet och vad som är viktigt"],
    ["en helig plats", "en plats som människor ser som särskilt viktig för sin religion"],
    ["en religiös ledare", "en person som leder eller undervisar en religiös grupp"],
    ["en psalm", "en religiös sång eller dikt"],
    ["en fasta", "att avstå från viss mat eller dryck under en bestämd tid"],
    ["en församling", "en grupp människor som hör till en religiös gemenskap"],
    ["en religiös ritual", "en handling som utförs på ett särskilt sätt inom en religion"],
  ],
  samhallskunskap: [
    ["demokrati", "ett sätt att styra där människor får vara med och bestämma"],
    ["en diktatur", "ett styre där en person eller liten grupp har nästan all makt"],
    ["en riksdag", "Sveriges folkvalda parlament som beslutar om lagar"],
    ["en regering", "gruppen som styr landet och genomför riksdagens beslut"],
    ["en kommun", "ett lokalt område som ansvarar för till exempel skola och omsorg"],
    ["en region", "ett område som bland annat ansvarar för sjukvård och kollektivtrafik"],
    ["en myndighet", "en del av staten som arbetar med en bestämd uppgift"],
    ["en lag", "en regel som gäller i ett land och som samhället beslutat om"],
    ["en regel", "en bestämmelse som hjälper människor att veta vad som gäller"],
    ["en skatt", "pengar som invånare och företag betalar till det gemensamma"],
    ["en budget", "en plan för inkomster och utgifter"],
    ["en inkomst", "pengar som en person eller ett hushåll får in"],
    ["en utgift", "pengar som en person eller ett hushåll betalar"],
    ["en lön", "pengar en arbetstagare får för sitt arbete"],
    ["en konsument", "en person som köper eller använder varor och tjänster"],
    ["en producent", "en person eller ett företag som tillverkar varor eller erbjuder tjänster"],
    ["en vara", "något som tillverkas och säljs"],
    ["en tjänst", "arbete eller hjälp som någon erbjuder mot betalning"],
    ["en rättighet", "något en människa har rätt att göra eller få"],
    ["ett ansvar", "något man förväntas ta hand om eller göra"],
    ["en skyldighet", "något man måste göra enligt en regel eller lag"],
    ["yttrandefrihet", "rätten att uttrycka sina tankar och åsikter"],
    ["tryckfrihet", "rätten att publicera texter utan förhandsgranskning från staten"],
    ["ett val", "ett tillfälle då människor röstar på vilka som ska representera dem"],
    ["en valsedel", "en papperssedel som används för att rösta i ett val"],
    ["en majoritet", "mer än hälften av en grupp"],
    ["en minoritet", "en mindre del av en grupp"],
    ["ett parti", "en grupp människor som vill påverka hur samhället styrs"],
    ["en motion", "ett förslag som en ledamot lämnar till riksdagen"],
    ["en omröstning", "när en grupp röstar för att fatta ett beslut"],
    ["en kompromiss", "en lösning där alla parter ger upp en del av sina önskemål"],
    ["en åsikt", "vad en person tycker om en fråga"],
    ["en källa", "den person eller det material som information kommer från"],
    ["källkritik", "att undersöka om information är trovärdig och användbar"],
    ["en nyhet", "information om något som nyligen har hänt"],
    ["en journalist", "en person som samlar in och berättar nyheter"],
    ["migration", "när människor flyttar från en plats eller ett land till ett annat"],
    ["integration", "när människor får möjlighet att delta i samhället"],
    ["en norm", "en oskriven förväntan om hur människor brukar göra"],
    ["diskriminering", "orättvis behandling på grund av vem någon är"],
    ["en konflikt", "en situation där personer eller grupper inte är överens"],
    ["en medling", "hjälp från en utomstående att lösa en konflikt"],
    ["ett samhälle", "människor som lever tillsammans och delar regler och service"],
    ["en välfärd", "gemensam trygghet och service som exempelvis skola och vård"],
    ["en medborgare", "en person som tillhör ett land enligt landets regler"],
  ],
  biologi: [
    ["fotosyntes", "processen där växter använder ljus för att bilda socker och syre"],
    ["cellandning", "processen där celler frigör energi ur socker med hjälp av syre"],
    ["en cell", "den minsta levande byggstenen i en organism"],
    ["en art", "en grupp organismer som kan få ungar tillsammans"],
    ["ett ekosystem", "alla organismer och den miljö de lever i på en plats"],
    ["en näringskedja", "en modell som visar vem som äter vem i naturen"],
    ["en näringsväv", "flera näringskedjor som hänger ihop"],
    ["en producent", "en organism, ofta en växt, som tillverkar sin egen näring"],
    ["en konsument", "ett djur som får energi genom att äta andra organismer"],
    ["en nedbrytare", "en organism som bryter ner döda växter och djur"],
    ["en växtätare", "ett djur som främst äter växter"],
    ["en rovdjur", "ett djur som jagar och äter andra djur"],
    ["en allätare", "ett djur som äter både växter och djur"],
    ["pollinering", "när pollen flyttas mellan blommor så att frön kan bildas"],
    ["ett frö", "en del av en växt som kan gro och bli en ny planta"],
    ["en grodd", "en ung växt som just har börjat växa från ett frö"],
    ["en rot", "den växtdel som ofta fäster växten och tar upp vatten"],
    ["en stjälk", "den växtdel som håller upp blad och blommor"],
    ["ett blad", "en växtdel som ofta fångar ljus och utför fotosyntes"],
    ["en blomma", "en växtdel där frön ofta bildas efter pollinering"],
    ["ett ryggradsdjur", "ett djur som har en ryggrad"],
    ["ett ryggradslöst djur", "ett djur som saknar ryggrad"],
    ["ett däggdjur", "ett ryggradsdjur vars ungar får mjölk från sin mamma"],
    ["en fågel", "ett ryggradsdjur med fjädrar och näbb"],
    ["en fisk", "ett ryggradsdjur som lever i vatten och andas med gälar"],
    ["en insekt", "ett leddjur med sex ben och en kropp i tre delar"],
    ["ett groddjur", "ett ryggradsdjur som ofta lever både i vatten och på land"],
    ["en livscykel", "de olika stadier en organism går igenom under sitt liv"],
    ["en livsmiljö", "den plats och de förhållanden där en organism lever"],
    ["en anpassning", "en egenskap som hjälper en organism att klara sin miljö"],
    ["predation", "samspelet där ett djur jagar och äter ett annat"],
    ["ett byte", "ett djur som jagas av ett rovdjur"],
    ["biologisk mångfald", "variation av arter och livsmiljöer i naturen"],
    ["en population", "alla individer av samma art som lever i ett område"],
    ["ett organ", "en del av kroppen som har en särskild uppgift"],
    ["hjärtat", "organet som pumpar blod genom kroppen"],
    ["lungorna", "organen där kroppen tar upp syre ur luften"],
    ["matsmältning", "när kroppen bryter ner mat så att näring kan tas upp"],
    ["ett skelett", "kroppens ben som ger stöd och skyddar organ"],
    ["en muskel", "en kroppsdel som kan dra ihop sig och skapa rörelse"],
    ["ett näringsämne", "ett ämne i maten som kroppen behöver för att fungera"],
    ["ett habitat", "en plats där en viss organism lever"],
    ["ett fröämne", "den del av en blomma som kan utvecklas till ett frö"],
    ["en svamp", "en organism som får näring genom att ta upp ämnen från sin omgivning"],
    ["en bakterie", "en mycket liten encellig organism"],
  ],
  fysik: [
    ["tyngdkraft", "kraften som drar föremål mot jorden"],
    ["friktion", "kraften som bromsar när ytor glider mot varandra"],
    ["en magnet", "ett föremål som kan dra till sig vissa metaller"],
    ["en kraft", "en påverkan som kan ändra ett föremåls rörelse eller form"],
    ["rörelseenergi", "energi som ett föremål har när det rör sig"],
    ["lägesenergi", "energi som beror på var ett föremål befinner sig"],
    ["värme", "energi som överförs från något varmare till något kallare"],
    ["temperatur", "ett mått på hur varmt eller kallt något är"],
    ["ljud", "vibrationer som färdas genom ett material och kan höras"],
    ["en vibration", "en snabb rörelse fram och tillbaka"],
    ["ljus", "energi som gör att vi kan se och som färdas mycket snabbt"],
    ["en skugga", "ett område dit ljuset inte når eftersom något står i vägen"],
    ["en reflektion", "när ljus studsar mot en yta"],
    ["en lins", "ett genomskinligt föremål som kan böja ljus"],
    ["en elektrisk krets", "en sluten väg där elektrisk ström kan gå"],
    ["elektrisk ström", "laddningar som rör sig genom en ledare"],
    ["en ledare", "ett material som släpper igenom elektrisk ström lätt"],
    ["en isolator", "ett material som leder elektrisk ström dåligt"],
    ["ett batteri", "en källa som kan ge elektrisk energi till en krets"],
    ["en strömbrytare", "en del som öppnar eller sluter en elektrisk krets"],
    ["energi", "förmågan att orsaka förändring eller utföra arbete"],
    ["solenergi", "energi som kommer från solen"],
    ["vindenergi", "energi som tas till vara från vindens rörelse"],
    ["vattenkraft", "energi som utvinns ur vatten i rörelse"],
    ["en förnybar energikälla", "en energikälla som fylls på naturligt på relativt kort tid"],
    [
      "en icke förnybar energikälla",
      "en energikälla som finns i begränsad mängd och tar lång tid att bilda",
    ],
    ["smältning", "när ett fast ämne blir flytande"],
    ["frysning", "när en vätska blir fast"],
    ["avdunstning", "när en vätska blir gas från sin yta"],
    ["kondensering", "när en gas kyls och blir vätska"],
    ["kokning", "när en vätska blir gas i hela vätskan"],
    ["en ljudkälla", "något som vibrerar och skapar ljud"],
    ["en ljudvåg", "en vibration som sprids genom luft eller annat material"],
    ["en tonhöjd", "hur hög eller låg en ton låter"],
    ["en hävstång", "en stång som kan vridas runt en stödpunkt för att förstärka en kraft"],
    ["ett lutande plan", "en sned yta som gör det lättare att flytta något uppåt"],
    ["ett kugghjul", "ett hjul med tänder som kan överföra rörelse"],
    ["en enkel maskin", "ett redskap som förändrar riktning eller storlek på en kraft"],
    ["en hastighet", "hur långt något rör sig under en viss tid"],
    ["en pendel", "ett föremål som svänger fram och tillbaka från en upphängning"],
    ["en våg", "en störning som sprider energi från en plats till en annan"],
    ["en isolering", "ett material eller lager som bromsar värmeöverföring"],
    ["ett kretslopp", "en följd av förändringar som upprepas om och om igen"],
    ["ett tillstånd", "en form som materia kan vara i, till exempel fast, flytande eller gas"],
    ["en blandning", "två eller flera ämnen som finns tillsammans utan att bli ett nytt ämne"],
  ],
  kemi: [
    ["en atom", "en mycket liten byggsten som ämnen består av"],
    ["en molekyl", "två eller flera atomer som sitter ihop"],
    ["ett grundämne", "ett ämne som består av en sorts atomer"],
    ["en kemisk förening", "ett ämne där olika sorters atomer sitter ihop"],
    ["en kemisk reaktion", "en förändring där nya ämnen bildas"],
    ["en blandning", "flera ämnen som finns tillsammans utan att vara kemiskt bundna"],
    ["en lösning", "en blandning där ett ämne har lösts jämnt i en vätska"],
    ["ett lösningsmedel", "en vätska som kan lösa ett annat ämne"],
    ["filtrering", "en metod att skilja fasta partiklar från en vätska med ett filter"],
    ["indunstning", "en metod där vätska får avdunsta så att löst ämne blir kvar"],
    ["destillering", "en metod som skiljer vätskor åt genom kokning och kondensering"],
    ["en indikator", "ett ämne som ändrar färg och kan visa om en lösning är sur eller basisk"],
    ["en syra", "ett ämne som kan ge sura egenskaper åt en lösning"],
    ["en bas", "ett ämne som kan motverka en syra"],
    ["neutral", "varken sur eller basisk"],
    ["pH", "en skala som visar hur sur eller basisk en lösning är"],
    ["förbränning", "en reaktion där ett ämne reagerar med syre och ofta avger värme"],
    ["syre", "en gas i luften som många organismer behöver för cellandning"],
    ["koldioxid", "en gas som bildas bland annat vid cellandning och förbränning"],
    ["vattenånga", "vatten i gasform"],
    ["smältpunkt", "den temperatur då ett fast ämne börjar bli flytande"],
    ["kokpunkt", "den temperatur då en vätska börjar koka"],
    ["fast form", "ett tillstånd där ett ämne har bestämd form och volym"],
    ["flytande form", "ett tillstånd där ett ämne har bestämd volym men tar kärlets form"],
    ["gasform", "ett tillstånd där ett ämne sprider ut sig och fyller tillgängligt utrymme"],
    ["rost", "ett ämne som bildas när järn reagerar med syre och vatten"],
    ["metall", "en materialgrupp som ofta leder värme och elektricitet bra"],
    ["plast", "ett material som ofta tillverkas av långa molekyler och kan formas"],
    ["återvinning", "att använda material igen i stället för att slänga det"],
    ["ett kretslopp", "när ett ämne används om och om igen i naturen"],
    ["vattenmolekyl", "en molekyl som består av två väteatomer och en syreatom"],
    ["H₂O", "den kemiska formeln för vatten"],
    ["ett salt", "ett ämne som kan bildas när en syra reagerar med en bas"],
    ["en fällning", "ett fast ämne som bildas i en vätska vid en kemisk reaktion"],
    ["en gas", "ett tillstånd där partiklarna rör sig fritt och långt ifrån varandra"],
    ["en partikel", "en mycket liten del av ett ämne"],
    ["en homogen blandning", "en blandning där de olika delarna inte syns var för sig"],
    ["en råvara", "ett material från naturen som används för att skapa produkter"],
    ["en egenskap", "något man kan observera eller mäta hos ett material"],
    ["en kemisk egenskap", "hur ett ämne kan förändras när det reagerar med andra ämnen"],
    ["en fysikalisk förändring", "en förändring där inget nytt ämne bildas"],
    ["en återvinningssymbol", "en symbol som kan visa hur en förpackning ska sorteras"],
    ["ett laboratorium", "en plats där man undersöker och experimenterar med ämnen"],
    ["en skyddsutrustning", "utrustning som skyddar kroppen vid laborationer"],
    ["en hypotes", "en möjlig förklaring som kan undersökas med ett test"],
  ],
  teknik: [
    ["en konstruktion", "en lösning som har byggts av flera delar"],
    ["en prototyp", "en första modell som används för att prova en idé"],
    ["en ritning", "en bild som visar hur något ska byggas eller se ut"],
    ["en skiss", "en enkel bild som visar en idé i ett tidigt skede"],
    ["en uppfinning", "en ny lösning eller produkt som någon har kommit på"],
    ["en innovation", "en ny eller förbättrad lösning som används i praktiken"],
    ["en mekanism", "delar som samarbetar för att överföra eller förändra rörelse"],
    ["en hävstång", "en stång som kan vridas kring en stödpunkt"],
    ["ett kugghjul", "ett hjul med tänder som kan föra rörelse vidare"],
    ["en kil", "ett redskap med spets som kan dela eller hålla isär material"],
    ["en skruv", "ett fäste med gängor som kan vridas in i material"],
    ["ett lutande plan", "en sned yta som gör det lättare att flytta saker uppåt"],
    ["en trissa", "ett hjul med ett spår som kan hjälpa till att lyfta med ett rep"],
    ["en axel", "en stång som ett hjul kan snurra runt"],
    ["ett hjul", "en rund del som kan rulla och minska motstånd"],
    ["en stabil konstruktion", "en konstruktion som står stadigt och inte välter lätt"],
    ["en triangulering", "att använda trianglar för att göra en konstruktion stadig"],
    ["en bro", "en konstruktion som gör att människor kan ta sig över ett hinder"],
    ["en hållfasthet", "hur bra ett material eller en konstruktion står emot krafter"],
    ["en belastning", "en kraft eller tyngd som påverkar en konstruktion"],
    ["en ledare", "ett material som leder elektrisk ström"],
    ["en isolator", "ett material som hindrar eller bromsar ström eller värme"],
    ["en strömbrytare", "en del som öppnar eller sluter en elektrisk krets"],
    ["en sensor", "en del som känner av en förändring i omgivningen"],
    ["en styrning", "en del som bestämmer hur en maskin eller ett system ska agera"],
    ["en robot", "en maskin som kan utföra uppgifter automatiskt"],
    ["en algoritm", "en tydlig följd av steg för att lösa ett problem"],
    ["programmering", "att skriva instruktioner som en dator kan följa"],
    ["en instruktion", "ett meddelande som talar om vad som ska göras"],
    ["en energikälla", "något som ger energi till en teknisk lösning"],
    ["solceller", "delar som omvandlar solljus till elektrisk energi"],
    ["en vindturbin", "en maskin som omvandlar vindens rörelse till el"],
    ["vattenkraft", "el som skapas med hjälp av vatten i rörelse"],
    ["återbruk", "att använda en sak igen i stället för att slänga den"],
    ["återvinning", "att ta vara på material så att det kan användas i nya produkter"],
    ["en kravspecifikation", "en lista över vad en teknisk lösning ska klara"],
    ["en testning", "att prova en lösning för att se om den fungerar"],
    ["en utvärdering", "att undersöka vad som fungerade bra och vad som kan förbättras"],
    ["en användare", "en person som använder en produkt eller tjänst"],
    ["ergonomi", "att utforma saker så att de fungerar bra för människokroppen"],
    ["en teknisk lösning", "ett sätt att använda kunskap och material för att lösa ett behov"],
    ["en råvara", "ett material från naturen som används för att tillverka saker"],
    ["ett material", "det ämne eller den blandning som något är gjort av"],
    ["en säkerhetsregel", "en regel som minskar risken för att någon skadas"],
    ["ett kretslopp", "ett system där material eller resurser används flera gånger"],
  ],
  "hem-och-konsumentkunskap": [
    ["en måltid", "mat och dryck som äts vid ett bestämt tillfälle"],
    ["en matsedel", "en plan för vilka måltider som ska lagas under en period"],
    ["en ingrediens", "en del som används när man lagar en maträtt"],
    ["ett recept", "en lista med ingredienser och instruktioner för att laga mat"],
    ["en portion", "den mängd mat som är tänkt för en person"],
    ["en hygien", "vanor som hjälper till att hålla kroppen och maten ren"],
    ["korskontaminering", "när bakterier förs från ett livsmedel eller en yta till ett annat"],
    ["en kylvara", "ett livsmedel som behöver förvaras kallt"],
    ["ett bäst före-datum", "datum som visar hur länge kvaliteten väntas vara bäst"],
    ["ett sista förbrukningsdatum", "datum efter vilket ett känsligt livsmedel inte bör ätas"],
    ["en innehållsförteckning", "en lista över ingredienserna i en matvara"],
    ["en näringsdeklaration", "information om näringsämnen och energi i en matvara"],
    ["ett näringsämne", "ett ämne i maten som kroppen behöver"],
    ["kolhydrater", "näringsämnen som ofta ger kroppen energi"],
    ["protein", "ett näringsämne som kroppen använder bland annat för att bygga muskler"],
    ["fett", "ett näringsämne som ger energi och hjälper kroppen att ta upp vissa vitaminer"],
    ["fiber", "delar av växter som hjälper matsmältningen"],
    [
      "en portion tallriksmodell",
      "en bild som visar hur en måltid kan fördelas mellan olika sorters mat",
    ],
    ["en livsmedelsmärkning", "information på en matvara om exempelvis innehåll eller produktion"],
    ["en miljömärkning", "en märkning som visar att en vara följer vissa miljökrav"],
    ["en budget", "en plan för pengar som kommer in och pengar som används"],
    ["en inkomst", "pengar som man får, till exempel lön eller veckopeng"],
    ["en utgift", "pengar som man betalar för något"],
    ["ett sparande", "pengar man lägger undan för att använda senare"],
    ["ett kvitto", "ett bevis på vad man har köpt och betalat"],
    ["ett erbjudande", "ett pris eller villkor som gäller under en viss tid"],
    ["jämförpris", "ett pris per kilo, liter eller annan enhet som gör varor lättare att jämföra"],
    ["en konsument", "en person som köper eller använder varor och tjänster"],
    ["en reklamation", "ett klagomål när en vara är felaktig"],
    ["en garanti", "ett löfte om att en vara ska fungera under en viss tid"],
    ["en hållbar konsumtion", "att välja och använda saker med hänsyn till miljö och resurser"],
    ["återbruk", "att använda en sak igen utan att först göra om materialet"],
    ["återvinning", "att göra material till råvara för nya produkter"],
    ["matsvinn", "mat som hade kunnat ätas men i stället slängs"],
    ["en säsongsvara", "en matvara som brukar finnas i större mängd under en viss del av året"],
    ["en råvara", "ett livsmedel eller material som används för att laga eller tillverka något"],
    [
      "en matförgiftning",
      "sjukdom som kan uppstå efter att man ätit mat med skadliga ämnen eller mikroorganismer",
    ],
    ["en temperaturzon", "ett temperaturområde som påverkar hur snabbt bakterier växer i mat"],
    ["en arbetsyta", "en yta där man förbereder eller lagar mat"],
    ["en diskborste", "ett redskap som används för att rengöra disk"],
    ["en städplan", "en plan för vilka städuppgifter som ska göras och när"],
    ["en tvättsymbol", "en symbol som visar hur ett plagg ska tvättas eller skötas"],
    ["en textil", "ett material som består av trådar eller fibrer"],
    ["en hushållsapparat", "en maskin som används i hemmet för en viss uppgift"],
    ["en elsäkerhet", "regler och vanor som minskar risken för elolyckor"],
  ],
  engelska: [
    ["apple", "äpple"],
    ["school", "skola"],
    ["friend", "vän"],
    ["family", "familj"],
    ["water", "vatten"],
    ["book", "bok"],
    ["window", "fönster"],
    ["morning", "morgon"],
    ["evening", "kväll"],
    ["winter", "vinter"],
    ["spring", "vår"],
    ["summer", "sommar"],
    ["autumn", "höst"],
    ["blue", "blå"],
    ["green", "grön"],
    ["yellow", "gul"],
    ["red", "röd"],
    ["happy", "glad"],
    ["tired", "trött"],
    ["hungry", "hungrig"],
    ["to read", "att läsa"],
    ["to write", "att skriva"],
    ["to speak", "att tala"],
    ["to listen", "att lyssna"],
    ["to play", "att leka eller spela"],
    ["to learn", "att lära sig"],
    ["to walk", "att gå"],
    ["to swim", "att simma"],
    ["big", "stor"],
    ["small", "liten"],
    ["fast", "snabb"],
    ["slow", "långsam"],
    ["beautiful", "vacker"],
    ["because", "därför att"],
    ["before", "före"],
    ["after", "efter"],
    ["between", "mellan"],
    ["under", "under"],
    ["always", "alltid"],
    ["sometimes", "ibland"],
    ["never", "aldrig"],
    ["yesterday", "i går"],
    ["tomorrow", "i morgon"],
    ["breakfast", "frukost"],
    ["lunch", "lunch"],
  ],
  svenska: [
    ["ett substantiv", "en ordklass för namn på personer, platser, saker och känslor"],
    ["ett verb", "en ordklass för sådant man gör eller något som händer"],
    ["ett adjektiv", "en ordklass som beskriver hur någon eller något är"],
    ["ett adverb", "en ordklass som ofta beskriver hur, när eller var något händer"],
    ["ett pronomen", "ett ord som kan stå i stället för ett substantiv"],
    ["en preposition", "ett ord som visar ett förhållande, till exempel i, på eller under"],
    ["en konjunktion", "ett ord som binder ihop ord eller meningar, till exempel och eller men"],
    ["en interjektion", "ett utropsord som ofta uttrycker en känsla eller reaktion"],
    ["en mening", "ord som tillsammans uttrycker en hel tanke"],
    ["en huvudsats", "en sats som kan stå ensam som en mening"],
    ["en bisats", "en sats som oftast behöver en huvudsats för att bli en hel mening"],
    ["ett subjekt", "den eller det som gör något i en mening"],
    ["ett predikat", "den del av meningen som berättar vad subjektet gör eller är"],
    ["ett objekt", "den eller det som påverkas av handlingen i en mening"],
    ["en synonym", "ett ord som betyder ungefär samma sak som ett annat ord"],
    ["en antonym", "ett ord som betyder motsatsen till ett annat ord"],
    ["en homonym", "ett ord som stavas eller låter likadant som ett annat men betyder något annat"],
    ["ett prefix", "en orddel som sätts framför ett ord och ändrar dess betydelse"],
    ["ett suffix", "en orddel som sätts efter ett ord och kan ändra dess form eller betydelse"],
    ["en sammansättning", "ett ord som har bildats genom att två eller flera ord satts ihop"],
    ["en stavelse", "en del av ett ord som innehåller ett vokalljud"],
    ["en vokal", "någon av bokstäverna a, e, i, o, u, y, å, ä och ö"],
    ["en konsonant", "en bokstav som inte är en vokal"],
    ["ett skiljetecken", "ett tecken som visar pauser eller meningars slut"],
    ["ett frågetecken", "ett skiljetecken som avslutar en direkt fråga"],
    ["ett utropstecken", "ett skiljetecken som kan visa ett starkt utrop"],
    ["ett kommatecken", "ett skiljetecken som visar en kort paus i en mening"],
    ["en dialog", "ett samtal mellan två eller flera personer i en text"],
    ["en berättare", "den röst som berättar vad som händer i en berättelse"],
    ["en huvudperson", "den person som berättelsen främst handlar om"],
    ["en miljö", "platsen och tiden där en berättelse utspelar sig"],
    ["en instruktion", "en text som berättar hur man ska göra något"],
    ["en faktatext", "en text som ger information om ett ämne"],
    ["en argumenterande text", "en text där någon framför åsikter och försöker övertyga"],
    ["en rubrik", "en kort text överst som berättar vad en text handlar om"],
    ["ett stycke", "en del av en text som samlar meningar om samma delämne"],
    ["en källa", "en person eller ett material som information kommer från"],
    ["källkritik", "att undersöka vem som gjort en källa och om den går att lita på"],
    ["en sammanfattning", "en kortare text som tar med det viktigaste från en längre text"],
    [
      "en liknelse",
      "ett bildligt uttryck där något jämförs med något annat med ord som som eller lik",
    ],
    ["en metafor", "ett bildligt uttryck där något beskrivs som något annat"],
    ["ett rim", "ord som har liknande ljud i slutet"],
    ["en vers", "en rad eller grupp av rader i en dikt eller sång"],
    ["en ordklass", "en grupp ord som fungerar på liknande sätt i språket"],
    ["en böjning", "en förändring av ett ords form, till exempel tal eller tempus"],
  ],
};

function conceptQuestions(facts: readonly [string, string][]): [string, string][] {
  return facts.flatMap(([term, definition]) => [
    [`Förklara begreppet ${term}.`, definition],
    [`Vilket begrepp beskrivs så här: ${definition}?`, term],
  ]);
}

const COMPLETE_QUESTION_BANK: Record<PlingSubject, readonly [string, string][]> = {
  geografi: [...QUESTION_BANK.geografi, ...conceptQuestions(CONCEPT_FACTS.geografi)],
  historia: [...QUESTION_BANK.historia, ...conceptQuestions(CONCEPT_FACTS.historia)],
  religion: [...QUESTION_BANK.religion, ...conceptQuestions(CONCEPT_FACTS.religion)],
  samhallskunskap: [
    ...QUESTION_BANK.samhallskunskap,
    ...conceptQuestions(CONCEPT_FACTS.samhallskunskap),
  ],
  biologi: [...QUESTION_BANK.biologi, ...conceptQuestions(CONCEPT_FACTS.biologi)],
  fysik: [...QUESTION_BANK.fysik, ...conceptQuestions(CONCEPT_FACTS.fysik)],
  kemi: [...QUESTION_BANK.kemi, ...conceptQuestions(CONCEPT_FACTS.kemi)],
  teknik: [...QUESTION_BANK.teknik, ...conceptQuestions(CONCEPT_FACTS.teknik)],
  "hem-och-konsumentkunskap": [
    ...QUESTION_BANK["hem-och-konsumentkunskap"],
    ...conceptQuestions(CONCEPT_FACTS["hem-och-konsumentkunskap"]),
  ],
  engelska: [...QUESTION_BANK.engelska, ...conceptQuestions(CONCEPT_FACTS.engelska)],
  svenska: [...QUESTION_BANK.svenska, ...conceptQuestions(CONCEPT_FACTS.svenska)],
};

function shuffle<T>(values: T[]): T[] {
  for (let i = values.length - 1; i > 0; i--) {
    const j = rand(0, i);
    [values[i], values[j]] = [values[j]!, values[i]!];
  }
  return values;
}

export function parseCustomPlingQuestions(value: string): {
  questions: [string, string][];
  invalidLines: number[];
} {
  const questions: [string, string][] = [];
  const invalidLines: number[] = [];
  const seen = new Set<string>();

  value.split(/\r?\n/).forEach((line, index) => {
    if (!line.trim()) return;
    const separator = line.indexOf(";");
    if (separator < 0) {
      invalidLines.push(index + 1);
      return;
    }
    const text = line.slice(0, separator).trim();
    const answer = line.slice(separator + 1).trim();
    if (!text || !answer) {
      invalidLines.push(index + 1);
      return;
    }
    const normalizedQuestion = text.replace(/\s+/g, " ").toLocaleLowerCase("sv-SE");
    if (seen.has(normalizedQuestion)) {
      invalidLines.push(index + 1);
      return;
    }
    seen.add(normalizedQuestion);
    questions.push([text, answer]);
  });

  return { questions, invalidLines };
}

export function generateSubjectPlingPlong(options: {
  subject: PlingSubject;
  customQuestions?: readonly [string, string][];
  tiles: number;
  plingCount: number;
}): PlingQuestion[] {
  const source = options.customQuestions ?? COMPLETE_QUESTION_BANK[options.subject];
  const uniqueQuestions = new Map<string, [string, string]>(
    source.map(([text, answer]) => [
      text.replace(/\s+/g, " ").toLocaleLowerCase("sv-SE"),
      [text, answer] as [string, string],
    ]),
  );
  if (uniqueQuestions.size < options.tiles) {
    throw new RangeError(
      `At least ${options.tiles} unique questions are required to create this game.`,
    );
  }

  const plingCount = Math.max(0, Math.min(options.tiles, Math.round(options.plingCount)));
  const questions = shuffle([...uniqueQuestions.values()])
    .slice(0, options.tiles)
    .map(([text, answer], index) => ({
      text,
      answer,
      pling: index < plingCount,
      word: true,
      geo: false,
    }));

  return shuffle(questions);
}
